- Crie uma lista de 1 milhão de elementos, onde cada elemento tem numeros aleatorios entre 1 e 20
- Agora calcule a soma de todos os elementos dessa lista
- Identifique o tempo que demora calcular a soma (pode usar a biblioteca ``time``)

In [ ]:
import time
import random

lista = []

for i in range(1000000):
  lista.append(random.randint(1,20))

init = time.time()
soma = sum(lista)
end = time.time()
print(end-init)

0.00594639778137207


1. Escreva um programa NumPy para criar uma matriz 3x4 preenchida com valores de 10 a 21.
   
   A saida esperada seria [[10, 11, 12, 13], [14, 15, 16, 17], [18, 19, 20, 21]]

In [ ]:
import numpy as np

matriz = np.arange(10,22).reshape(3,4)
print(matriz)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


2. Escreva um programa NumPy para criar uma matriz bidimensional 8x5 de números aleatórios. Selecione números aleatórios entre 10 e 25.

In [ ]:
import numpy as np

matriz = np.random.randint(10, high=26, size=(8, 5))
print(matriz)

[[24 18 19 14 20]
 [24 25 19 20 22]
 [24 13 23 10 19]
 [11 25 13 16 12]
 [23 16 20 12 24]
 [18 12 15 14 11]
 [22 24 11 14 19]
 [16 24 14 20 14]]


3. Escreva um programa NumPy para criar uma matriz 10x10, na qual os elementos nas bordas serão iguais a 1 e no interior 0.

In [ ]:
import numpy as np

matriz = np.zeros((10,10),dtype=int)
matriz[0,:] = 1
matriz[-1,:] = 1
matriz[:,0] = 1
matriz[:,-1] = 1
print(matriz)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [ ]:
matriz = np.ones((10,10),dtype=int)
matriz[1:-1,1:-1] = 0
print(matriz)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


4. Usando como base o 'Exercício de aquecimento', compare quanto demora somar um vetor da forma convencional e usando Numpy.

In [ ]:
import time

vetor = np.random.randint(1, high=21, size=(1000000, 1))
init = time.time()
soma = np.sum(vetor)
end = time.time()
print(end-init)

0.0008072853088378906
