## Análise de transações financeiras com NumPy

A biblioteca NumPy é uma ferramenta amplamente utilizada na área financeira para a análise de grandes conjuntos de dados, principalmente na detecção de fraudes bancárias. Como analista de dados de uma instituição financeira, você foi designado para analisar transações financeiras a fim de identificar possíveis fraudes. A instituição coleta os dados das transações realizadas e armazena-os em arrays NumPy. Escreva uma função chamada `analisa_transacoes`, que recebe como entrada um array NumPy de valores de transações e retorna um array NumPy do tipo **float64** com as seguintes medidas estatísticas:
- Média;
- Valor mínimo;
- Valor máximo;

Com essas medidas estatísticas, a instituição poderá identificar possíveis padrões e anomalias nos dados das transações, que podem ser sinais de atividades fraudulentas.

Dica: Utilize as funções disponíveis no NumPy para calcular cada medida estatística.

Exemplo:

```python

transacoes = np.array([100.0, 200.0, 50.0, 300.0, 250.0, 120.0, 80.0, 500.0])

analisa_transacoes(transacoes)

>>> array([200.0, 50.0,  500.0])
```

In [ ]:
import numpy as np

def analisa_transacoes(matriz: np.ndarray) -> np.ndarray:
    media    = np.mean(matriz)
    minimo   = np.min(matriz)
    maximo   = np.max(matriz)
    return np.array([media,minimo,maximo],dtype=np.float64)

transacoes = np.array([100.0, 200.0, 50.0, 300.0, 250.0, 120.0, 80.0, 500.0])

analisa_transacoes(transacoes)

array([200.,  50., 500.])

## Cálculo da soma dos elementos de cada coluna em uma matriz usando NumPy

O processamento digital de imagens é uma área que utiliza técnicas computacionais para processar e analisar imagens digitais. Uma das bibliotecas utilizadas nessa área é o NumPy, uma biblioteca Python que permite trabalhar com matrizes multidimensionais e oferece diversas funções e operações matemáticas.

Suponha que você seja um desenvolvedor de software de processamento digital de imagens e foi designado para criar uma função que calcule a soma dos elementos de cada coluna de uma matriz de entrada. A matriz de entrada pode ter qualquer tamanho e é armazenada como um array NumPy.

Assinatura da função: `soma_colunas(matriz: np.ndarray) -> np.ndarray`

Exemplo:

```python

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

soma = soma_colunas(matriz)

>>> array([12, 15, 18])
```


In [ ]:
import numpy as np

#sem np.sum
def soma_colunas(matriz: np.ndarray) -> np.ndarray:
    aux  = np.ones((matriz.shape[1]),dtype=np.uint8)
    soma = matriz.T @ aux
    return soma

def soma_colunas_v2(matriz: np.ndarray) -> np.ndarray:
  return np.sum(matriz,axis=0)

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz)

soma  = soma_colunas(matriz)
soma2 = soma_colunas_v2(matriz)

print(soma)
print(soma2)

matriz = np.array([[7, 10, 3], [2, -1, 0], [6, -10, 9]])
print(matriz)

soma = soma_colunas(matriz)
soma2 = soma_colunas_v2(matriz)

print(soma)
print(soma2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[12 15 18]
[[  7  10   3]
 [  2  -1   0]
 [  6 -10   9]]
[15 -1 12]
[15 -1 12]


## Criação de uma Matriz Identidade Usando NumPy

No processamento digital de imagens, é comum utilizar matrizes para representar imagens e aplicar operações matemáticas sobre elas. Uma operação comum é a multiplicação de uma matriz por um escalar, que pode ser usado para ajustar o brilho ou a intensidade de cores de uma imagem. O NumPy é uma biblioteca do Python que permite trabalhar com matrizes multidimensionais e oferece diversas funções e operações matemáticas.

Nesse contexto, crie uma função chamada `cria_matriz_identidade` que receba dois parâmetros: o tamanho da matriz (*n*) e o fator de multiplicação (*m*). A função deve retornar uma matriz identidade de tamanho *n x n* multiplicada pelo fator *m*, representada como um array numpy.

Assinatura da função: `cria_matriz_identidade(n:int, m:float) -> np.ndarray`

Exemplo:

```python

cria_matriz_identidade(3, 2)

>>> array([[2., 0., 0.],
           [0., 2., 0.],
           [0., 0., 2.]])
```

In [ ]:
def cria_matriz_identidade(n:int, m:float) -> np.ndarray:
    identidade = np.identity(n)
    matriz     = m * identidade
    return matriz

print(cria_matriz_identidade(3, 2))
print(cria_matriz_identidade(4, -1))

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
[[-1. -0. -0. -0.]
 [-0. -1. -0. -0.]
 [-0. -0. -1. -0.]
 [-0. -0. -0. -1.]]
